# Generated by Django 4.2.11 on 2024-04-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, null=True)),
                ('uploaded', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
