# Generated by Django 4.2.11 on 2024-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='age_rating',
            field=models.CharField(choices=[('18', '18+'), ('15', '15+'), ('12', '12+'), ('7', '7+'), ('unrated', 'Unrated')], max_length=8),
        ),
    ]
