# Generated by Django 4.2.11 on 2024-04-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_age_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videos.video')),
                ('lead_actor', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(choices=[('18', '18+'), ('15', '15+'), ('12', '12+'), ('7', '7+'), ('unrated', 'Unrated')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videos.video')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='age_rating',
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded', models.DateTimeField()),
                ('path', models.CharField(max_length=255)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.resource')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='videos.series')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.resource'),
        ),
    ]
