# Generated by Django 4.2.11 on 2024-04-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.resource')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='path',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='resource',
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.resource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('clip', 'Clip'), ('other', 'Other')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.show'),
        ),
        migrations.AddField(
            model_name='clip',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='videos.season'),
            preserve_default=False,
        ),
    ]
