# Generated by Django 4.2.11 on 2024-04-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_video_path_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extension',
            field=models.CharField(default='.mp4', max_length=8),
        ),
    ]
