# Generated by Django 4.2.13 on 2024-07-07 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_uservideotimestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('file_extension', models.CharField(editable=False, max_length=8)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
    ]
