# Generated by Django 4.2.13 on 2024-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_episode_number_season_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
