# Generated by Django 4.2.13 on 2024-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_season_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
