# Generated by Django 4.2.13 on 2024-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_alter_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
